name: Android CI

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:

  lint:
    name: Run List Checks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2
        
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Run lint checks
        run: ./gradlew lintDebug

      - name: Upload lint report
        uses: actions/upload-artifact@v2
        with:
          name: lint_checks_report
          path: app/build/reports/
          
  unit-test:
    needs: [lint]
    name: Run Unit Tests
    runs-on: ubuntu-latest
    steps:
    
      - name: Checkout the code
        uses: actions/checkout@v2
        
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
        
      - name: Run tests
        run: ./gradlew test
        
      - name: Upload test report
        uses: actions/upload-artifact@v2
        with:
          name: unit_test_report
          path: app/build/reports/tests/testDebugUnitTest/

  instrumentation-test:
    needs: [unit-test]
    name: Run Instrumented Tests
    runs-on: macos-latest
    strategy:
      matrix:
        api-level: [ 29 ]
        target: [ google_apis ]
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Run instrumented tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ matrix.api-level }}
          target: ${{ matrix.target }}
          arch: x86_64
          profile: Nexus 6
          script: ./gradlew connectedCheck

      - name: Upload instrumented test report
        uses: actions/upload-artifact@v2
        with:
          name: instrumented_test_report
          path: app/build/reports/androidTests/connected/